name: Build and Deploy Zola Site

on:
  push:
    branches:
      - zola
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install Zola
        run: |
          wget -q -O - "https://github.com/getzola/zola/releases/download/v0.22.1/zola-v0.22.1-x86_64-unknown-linux-gnu.tar.gz" | tar xzf -
          sudo mv zola /usr/local/bin
          zola --version

      - name: Build with Zola
        run: |
          cd zdocs
          zola build --base-url ${{ ZOLA_BASE_URL }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./zdocs/public

  deploy:
    environment:
      name: github-pages
      url: ${{ ZOLA_BASE_URL }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
